[application]
name = "ESV Bible"
# Currently supported platforms: web, desktop
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
# HTML title tag content
title = "ESV Bible"
favicon = "./favicon.ico"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]
index_on_404 = true

[web.resource]
style = [
    # Include from public_dir.
    "./tailwind.css",
]
favicon = "./favicon.ico"


[web.resource.dev]
style = [
    # Include from public_dir.
    "./tailwind.css",
]
favicon = "./favicon.ico"

[[web.proxy]]
backend = "http://localhost:8000/api/"
